# Generated by Django 3.1.5 on 2021-02-21 21:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default='', max_length=200, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
    ]
