# Generated by Django 3.1.5 on 2021-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210221_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(default=0, verbose_name='Id'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author_id',
            field=models.IntegerField(default=0, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
