# Generated by Django 3.1.5 on 2021-03-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20210223_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_theme',
            field=models.IntegerField(default=0, max_length=50, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=20, verbose_name='Name'),
        ),
    ]
