# Generated by Django 3.1.5 on 2021-03-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20210314_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_theme',
            field=models.CharField(default='', max_length=200, verbose_name='options'),
        ),
    ]
