# Generated by Django 3.1.5 on 2021-03-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20210314_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_theme',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_subject',
            field=models.TextField(default='', verbose_name='options'),
        ),
    ]
