# Generated by Django 3.1.5 on 2021-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20210314_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_subject',
            field=models.IntegerField(default=0, verbose_name='options'),
        ),
    ]
